### ISSUE TITLE
Problem with word level alignment

### ISSUE THREAD

**Issue by stdoo** [A2Zadeh/CMU-MultimodalSDK#115]
I think there's something wrong in the word level alignment.
My code:
```
import numpy

from mmsdk import mmdatasdk


def myavg(intervals, features):
    return numpy.average(features, axis=0)


# read dataset by folder
cmumosi_highlevel = mmdatasdk.mmdataset('./cmumosi/')

cmumosi_highlevel.align('glove_vectors', collapse_functions=[myavg])

cmumosi_highlevel.align('Opinion Segment Labels')

deploy_files = {x: x for x in cmumosi_highlevel.computational_sequences.keys()}
cmumosi_highlevel.deploy("./deployed", deploy_files)
```

error:
```
Computational Sequence Entries/sTraceback (most recent call last):                                                   | 0/1 [00:00<?, ? Segments/s]
  File "read_dataset_align.py", line 37, in <module>
    cmumosi_highlevel.align('Opinion Segment Labels')
  File "/home/yangbo/anaconda3/envs/nlp/lib/python3.6/mmsdk/mmdatasdk/dataset/dataset.py", line 121, in align
    entry_key], epsilon)
KeyError: '03bSnISJMiM[110]'
```

I think I know where the error comes from, during the first align, you construct the aligned output like this:

`aligned_output[otherseq_key][entry_key + "[%d]" % i] = {}`

So the entry_key(video key) is changed with the additional '[i]', then you construct new computational sequences with aligned_output, so the new sequence has video key with additional '[i]'.

In the second align, when you call the __intersect_and_copy with relevant_entries[otherseq_key][entry_key], which has split entry_key with '[', it will raise a KeyError, because relevant_entries can't recognize entry_key with additional '[i]'

**Comment by stdoo** [comment]
It's because of my code, when I read dataset by folder, the entire cmumosi is read, including the Opinion Segment Labels. So in the first align, the Opinion Segment Labels is also aligned with glove_vector and lead to additional '[i]' in video_key, that's why the second align failed.

**Comment by Imorton-zd** [comment]
Hi, @stdoo @A2Zadeh  . I follow the word_level_align.py for mosi dataset, but I met the collapsing problem.

```
<Success>: Computational sequence read from file cmumosi/CMU_MOSI_OpenSmile_EB10.csd ...
<Status>: Checking the integrity of the data in <OpenSmile-emobase2010> computational sequence ...
<Success>: <OpenSmile-emobase2010> computational sequence data in correct format.
<Status>: Checking the integrity of the metadata in <OpenSmile-emobase2010> computational sequence ...
<Success>: <OpenSmile-emobase2010> computational sequence metadata in correct format
<Success>: Computational sequence read from file cmumosi/CMU_MOSI_VisualFacet_4.1.csd ...
<Status>: Checking the integrity of the data in <FACET 4.1> computational sequence ...
<Success>: <FACET 4.1> computational sequence data in correct format.  
<Status>: Checking the integrity of the metadata in <FACET 4.1> computational sequence ...
<Success>: <FACET 4.1> computational sequence metadata in correct format
<Success>: Computational sequence read from file cmumosi/CMU_MOSI_OpenFace2.csd ...
<Status>: Checking the integrity of the data in <OpenFace> computational sequence ...
<Success>: <OpenFace> computational sequence data in correct format.   
<Status>: Checking the integrity of the metadata in <OpenFace> computational sequence ...
<Success>: <OpenFace> computational sequence metadata in correct format
<Success>: Computational sequence read from file cmumosi/CMU_MOSI_COVAREP.csd ...
<Status>: Checking the integrity of the data in <COAVAREP> computational sequence ...
<Success>: <COAVAREP> computational sequence data in correct format.   
<Status>: Checking the integrity of the metadata in <COAVAREP> computational sequence ...
<Success>: <COAVAREP> computational sequence metadata in correct format
<Success>: Computational sequence read from file cmumosi/CMU_MOSI_openSMILE_IS09.csd ...
<Status>: Checking the integrity of the data in <OpenSMILE> computational sequence ...
<Success>: <OpenSMILE> computational sequence data in correct format.  
<Status>: Checking the integrity of the metadata in <OpenSMILE> computational sequence ...
<Success>: <OpenSMILE> computational sequence metadata in correct format
<Success>: Computational sequence read from file cmumosi/CMU_MOSI_TimestampedWordVectors_1.1.csd ...
<Status>: Checking the integrity of the data in <glove> computational sequence ...
<Success>: <glove> computational sequence data in correct format.      
<Status>: Checking the integrity of the metadata in <glove> computational sequence ...
<Success>: <glove> computational sequence metadata in correct format
<Success>: Dataset initialized successfully ... 
<Status>: Unify was called ...
<Success>: Unify completed ...
<Status>: Alignment based on <glove_vectors> computational sequence will start shortly ...
Overall Progress:   0%| | 0/93 [00:00<?, ? Computational Sequence Entries/s]                                                                 Traceback (most recent call last):       | 0/667 [00:00<?, ? Segments/s]
  File "data_loader.py", line 358, in <module>
    test_mosei_emotion_data()
  File "data_loader.py", line 217, in test_mosei_emotion_data
    mosei_dataset.align('glove_vectors',collapse_functions=[myavg])
  File "/home/dzhang/AAAI/2020/SGM-master/mmsdk/mmdatasdk/dataset/dataset.py", line 131, in align
    intersects,intersects_features=self.__collapse(intersects,intersects_features,collapse_functions)
  File "/home/dzhang/AAAI/2020/SGM-master/mmsdk/mmdatasdk/dataset/dataset.py", line 160, in __collapse
    log.error("Cannot collapse given the set of function.", error=True)
  File "/home/dzhang/AAAI/2020/SGM-master/mmsdk/mmdatasdk/log/log.py", line 18, in error
    action("%s%s"%(msgstart,msgstring))
  File "/home/dzhang/AAAI/2020/SGM-master/mmsdk/mmdatasdk/log/log.py", line 17, in <lambda>
    action,msgstart=(lambda x:(_ for _ in ()).throw(errorType(x)),"<Error>: ") if error else (lambda x:sys.stdout.write(str(x)+'\n'),bcolors.WARNING+bcolors.BOLD+"<Warning>: "+bcolors.ENDC)
  File "/home/dzhang/AAAI/2020/SGM-master/mmsdk/mmdatasdk/log/log.py", line 17, in <genexpr>
    action,msgstart=(lambda x:(_ for _ in ()).throw(errorType(x)),"<Error>: ") if error else (lambda x:sys.stdout.write(str(x)+'\n'),bcolors.WARNING+bcolors.BOLD+"<Warning>: "+bcolors.ENDC)
RuntimeError: <Error>: Cannot collapse given the set of function.
```
I use the following code and .csd files:
```
mosi_dataset = mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')
mosi_dataset.align('glove_vectors',collapse_functions=[myavg])
mosi_dataset.add_computational_sequences(mmdatasdk.cmu_mosi.labels,'cmumosi/')
mosi_dataset.align('Opinion Segment Labels')
deploy_files={x:x for x in mosi_dataset.computational_sequences.keys()}
mosi_dataset.deploy("./deployed",deploy_files)
aligned_cmumosi_highlevel=mmdatasdk.mmdataset('./deployed')
    
print ('fea name', aligned_cmumosi_highlevel.keys())
```

![image](https://user-images.githubusercontent.com/13865086/60066829-d93c0f00-973a-11e9-8080-59da67d78781.png)

**Comment by A2Zadeh** [comment]
@Imorton-zd Hmm interesting. What is your collapse function? myavg in the example? Also did you pull the most recent SDK? I just did this and seems like it works. 

BTW, the BERT embeddings were not correct the first time I created them. They were contextual beyond the boundary of the segment. I am creating a new one soon.

**Comment by Imorton-zd** [comment]
@A2Zadeh Thanks for your reply. I'm sorry that it is the error of my collapse function. Now the above code is already running. The great work of your shared multimodal-sdk!
