### ISSUE TITLE
Download link doesn't work

### ISSUE THREAD

**Issue by kavya-45** [A2Zadeh/CMU-MultimodalSDK#306]
@A2Zadeh
Hi Amir,
Your download link doesn't work http://immortal.multicomp.cs.cmu.edu/cache/ how can I get raw labels for CMU-MOSI please help me. Thanks in advance.

**Comment by Oliviaorange** [comment]
Yeah, I have the same problem. I need this dataset urgently. Is there anyone who has downloaded this dataset could share a link? Thanks!

**Comment by Hiroaki-K4** [comment]
I have save problem.
And when I ran it with the code below, I got an error.
```
>>> from mmsdk import mmdatasdk
>>> cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')
```
The error message is as below.
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe5d51ce0a0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='immortal.multicomp.cs.cmu.edu', port=80): Max retries exceeded with url: /CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5d51ce0a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hiroaki-k4/work/CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/dataset.py", line 30, in __init__
    self.computational_sequences[entry]=computational_sequence(address,destination)
  File "/home/hiroaki-k4/work/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 33, in __init__
    self.__initialize(resource,destination,validate)
  File "/home/hiroaki-k4/work/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 116, in __initialize
    self.__initialize_from_csd(resource,destination,validate)
  File "/home/hiroaki-k4/work/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 76, in __initialize_from_csd
    read_URL(resource,destination)
  File "/home/hiroaki-k4/work/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/download_ops.py", line 21, in read_URL
    r = requests.get(url, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='immortal.multicomp.cs.cmu.edu', port=80): Max retries exceeded with url: /CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5d51ce0a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
Is there any solution? Thanks!

**Comment by Cristeen20** [comment]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='immortal.multicomp.cs.cmu.edu', port=80): Max retries exceeded with url: /CMU-MOSEI/language/CMU_MOSEI_TimestampedWords.csd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EB6C007E80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))


This is the error I get when I tried to download the dataset using
-source={"raw":mmdatasdk.cmu_mosei.raw,"highlevel":mmdatasdk.cmu_mosei.highlevel,"labels":mmdatasdk.cmu_mosei.labels}

**Comment by Cristeen20** [comment]
`raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='immortal.multicomp.cs.cmu.edu', port=80): Max retries exceeded with url: /CMU-MOSEI/language/CMU_MOSEI_TimestampedWords.csd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EB6C007E80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))`

**Comment by Cristeen20** [comment]
https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/304#issuecomment-890174700

see this folks

**Comment by A2Zadeh** [comment]
Hi folks,

Sorry this took long. I just finished my Ph.D. and was busy finalizing things. Next week the server will be up.

**Comment by kiva12138** [comment]
Now 14 days past, and the link is still not working......

**Comment by souravBhat** [comment]
Hi @A2Zadeh, can we please get an update on this?

**Comment by kiva12138** [comment]
The link seems online. But when accesing the files, the server will return the "403 Forbidden".

**Comment by A2Zadeh** [comment]
Hi all,

This issue is now resolved.
