### ISSUE TITLE
Word Level Alignement

### ISSUE THREAD

**Issue by XinyuLyu** [A2Zadeh/CMU-MultimodalSDK#57]
I think there maybe sth wrong in Word Level Alignment operations. If I don't do Word Level Alignment operations, I can easily open all the .csd files.
After finishing the last step in Word Level Alignment operations, I find I can not open the .csd files with the following codes. And there is an error ' CMU_MOSI_TimestampedWordVectors.csd resource is not a valid hdf5 computational sequence  ...' . 
    >>> import mmsdk 
    >>> from mmsdk import mmdatasdk 
    >>> mydict={'myfeatures':'CMU_MOSI_VisualFacet_4.1.csd'} 
    >>> mydataset=mmdatasdk.mmdataset(mydict) 
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
      File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/dataset.py", line 17, in __init__
    self.computational_sequences[entry] = computational_sequence(address, destination)
      File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 32, in __init__h5handle,data,metadata=self._initialize(resource,destination)
      File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 75, in _initialize return readCSD(self.mainFile)
  File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/file_ops.py", line 15, in readCSD raise log.error("%s resource is not a valid hdf5 computational sequence  ..."%resource,error=True)
  File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/log/log.py", line 18, in error
    action("%s%s"%(msgstart,msgstring))
  File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/log/log.py", line 17, in <lambda>
    action,msgstart=(lambda x:(_ for _ in ()).throw(errorType(x)),"<Error>: ") if error else (lambda x:sys.stdout.write(str(x)+'\n'),bcolors.WARNING+bcolors.BOLD+"<Warning>: "+bcolors.ENDC)
  File "/Users/xinyu/CMU-MultimodalSDK/mmsdk/mmdatasdk/log/log.py", line 17, in <genexpr>
    action,msgstart=(lambda x:(_ for _ in ()).throw(errorType(x)),"<Error>: ") if error else (lambda x:sys.stdout.write(str(x)+'\n'),bcolors.WARNING+bcolors.BOLD+"<Warning>: "+bcolors.ENDC)
RuntimeError: <Error>: CMU_MOSI_TimestampedWordVectors.csd resource is not a valid hdf5 computational sequence  ...

**Comment by XinyuLyu** [comment]
I'm not sure what the deploy function means. I call all the codes in Word Level Alignment operations with the code below. 
<code></code>
<code></code>
<code></code>
<code></code>

**Comment by XinyuLyu** [comment]
I'm not sure what the deploy function means. You mean the <code>collapse_functions=[myavg]</code>? For that parameter, I set it to be 'default'. I call all the codes in Word Level Alignment operations with the codes below.
<code>>>> from mmsdk import mmdatasdk</code>
<code>>>> cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')</code>
<code>>>> cmumosi_highlevel.align('glove_vectors')</code>
<code>>>> cmumosi_highlevel.add_computational_sequence(mmdatasdk.cmu_mosi.labels,'cmumosi/')</code>
<code>>>> cmumosi_highlevel.align('Opinion Segment Labels')</code>
Then I try to open the csd files with the codes I have mentioned. Then it give me the error information I have mentioned before.

**Comment by A2Zadeh** [comment]
You need to mention "cmumosi/CMU_MOSI_VisualFacet_4.1.csd" in your dictionary.

**Comment by XinyuLyu** [comment]
Thank you so much!
